services: 
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./backend:/transcendence
    restart: always
    networks:
      - transcendence
    env_file:
      - .env
    depends_on:
      - backend

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/transcendence
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - transcendence
    env_file:
      - .env

  backend:
    container_name: django
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/transcendence
    env_file:
      - .env
    networks:
      - transcendence
    restart: unless-stopped
    depends_on:
      - db
  
  db:
    container_name: postgreSQL
    image: postgres:alpine3.19
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - transcendence
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - transcendence
    restart: always

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.1
    container_name: logstash
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
    networks:
      - transcendence
    restart: always
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - transcendence
    restart: always
    depends_on:
      - elasticsearch

networks:
  transcendence:

volumes:
  postgres_data:
  esdata: