# Generated by Django 4.2.11 on 2024-04-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('num_games', models.IntegerField(default=0)),
                ('num_games_won', models.IntegerField(default=0)),
                ('num_tournaments', models.IntegerField(default=0)),
                ('num_tournaments_won', models.IntegerField(default=0)),
            ],
        ),
    ]
