# Generated by Django 4.2.13 on 2024-05-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0004_user_is_2fa_enabled_user_two_factor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='two_factor_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
