# Generated by Django 4.2.11 on 2024-04-25 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0004_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_accepted', models.BooleanField(default=False)),
                ('was_canceled', models.BooleanField(default=False)),
                ('was_refused', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_users', to='transcendence.tournament')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_users', to='transcendence.user')),
            ],
        ),
    ]
