# Generated by Django 4.2.11 on 2024-05-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0008_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
