# Generated by Django 4.2.13 on 2024-05-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0011_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
