# Generated by Django 4.2.13 on 2024-05-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0011_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='./media/avatar.jpeg', upload_to='avatars/'),
            preserve_default=False,
        ),
    ]
