# Generated by Django 4.2.13 on 2024-05-14 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0012_friendrequest_chat_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 14, 22, 30, 0, 0, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
