# Generated by Django 4.2.13 on 2024-05-17 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0012_alter_match_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
