# Generated by Django 4.2.13 on 2024-05-21 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0014_alter_match_created_on'),
    ]

    operations = [
    ]
