# Generated by Django 4.2.13 on 2024-05-23 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0004_user_is_active_user_is_authenticated'),
        ('transcendence', '0016_tournament_created_on_alter_tournament_id'),
    ]

    operations = [
    ]
